# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 830cd424ac734b8ecbd65a64b4cd297ce552f37c38ce03e32828927ed33164093422133e618ea4fb7c8e917d9a4d264d6cb03310719aa21220e06d1cb9eb46c2

test:
  secret_key_base: 658e9cd6d4c7d738cb1a42ee85faca94d45d0f6d2f7e115f5c528e7a2ab71aa3e84b80534fac9b841c094591d54c7764ed57c6a475085b236b0236c14f2991f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
